Add controllers
Anastassvirs/java-shareit pull request #1
Opened 2023-01-17 03:47 UTC by Anastassvirs

2023-01-17 07:29 UTC, Frilock requested changes
Добрый день, посмотрел работу, из основных комментариев:
1. Логику из контроллеров нужно перенести в сервис
2. Обработку ошибок можно сделать через специальный обработчик - статью приложил
3. Не понял идею с 2мя коллекциями, зачем?
4. Если у Вас одна реализация интерфейса то Qualifier не нужен

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exceptions/AlreadyExistException.java
> +package ru.practicum.shareit.exceptions; // Вопрос в том, нормально ли в такой структуре папок оставлять папку с ошибками
Думаю да

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        } catch (NotFoundAnythingException e) {
Чтобы такую штуку не делать можете сделать обработчик для исключений
https://struchkov.dev/blog/exception-handling-controlleradvice/

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            Item item = itemService.findById(itemId);
Данную логику нужно перенести в сервис, в контролере оставьте только вызов метода сервиса

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                if (itemDto.getDescription() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @DeleteMapping()
Пустые скобки не нужны

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        for (Item oldItem: storage.findAll()) {
после oldItem пробел, а вообще перед коммитом воспользуйтесь в IDEA галочкой автоформатирование кода, чтобы не заморачиваться

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/InMemoryItemStorage.java
> +    private HashMap<Long, Item> items;
А зачем две коллекции? Почему одной не обойтись?

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/InMemoryItemStorage.java
> +        items = new HashMap();
Забыли this

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/InMemoryItemStorage.java
> +            if (item.getAvailable() && (item.getName().toLowerCase().contains(text.toLowerCase())
Можно воспользоваться StringUtils.containsIgnoreCase

2023-01-17 07:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/InMemoryUserStorage.java
> +@Qualifier("memoryUserStorage")
А вообще зачем Вам Qualifier если у Вас одна реализация?

2023-01-18 03:51 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/user/dto/InMemoryUserStorage.java
> +@Qualifier("memoryUserStorage")
Просто в тз было сказано, что в дальнейших спринтах будет версия с бд и я заранее сделала, чтобы не забыть потом

2023-01-18 04:13 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        } catch (NotFoundAnythingException e) {
точно.. мы же это делали еще в filmorate.Спасибо!

2023-01-18 06:35 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/InMemoryUserStorage.java
> +@Qualifier("memoryUserStorage")
У Вас работать потом не будет, если забудете =) Лучше вообще заранее не делать, а идти маленькими шажками не распыляясь

2023-01-18 06:40 UTC, Frilock requested changes
Добрый день, уже хорошо, но все равно есть ряд нюансов. Основной, я все равно не понял зачем Вам две коллекции в некоторых классах. Можете либо переделать на одну, либо в комментарии просто объясните логику.

2023-01-18 06:40 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Item> create(@Valid @RequestBody ItemDto item, @RequestHeader(value = "X-Sharer-User-Id") Long ownerId) {
А без Validated над классом валидация у Вас работать то будет? Проверили?)

2023-01-18 06:40 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/ItemDto.java
> +    public ItemDto(String name, String description, Boolean available, Long requestId) {
Можно AllArgsConstructor от ломбока, и тогда этот можно убрать

2023-01-18 06:40 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/dto/InMemoryRequestStorage.java
> +    private List<ItemRequest> listrequests;
А тут зачем 2 коллекции? В одном из классов убрали, а во втором нет, мб какая то логика интересная тут присутствует, можете мне в комментарии объяснить тогда

2023-01-18 14:54 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Item> create(@Valid @RequestBody ItemDto item, @RequestHeader(value = "X-Sharer-User-Id") Long ownerId) {
Да, аннотация @Valid в используется для проверки на уровне метода, а Validated - для групповой валидации. Вот ссылка на статью, где я об этом прочитала: https://www.baeldung.com/spring-valid-vs-validated

2023-01-18 14:55 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Item> create(@Valid @RequestBody ItemDto item, @RequestHeader(value = "X-Sharer-User-Id") Long ownerId) {
Ну и добавила я ее именно потому, что тесты не проходили, в которых нужна была проверка, так что она точно работает

2023-01-18 15:00 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/item/model/ItemDto.java
> +    public ItemDto(String name, String description, Boolean available, Long requestId) {
Исправила. В других классах, вроде, нет возможности такой замены

2023-01-18 15:05 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/request/dto/InMemoryRequestStorage.java
> +    private List<ItemRequest> listrequests;
Нет, логики никакой нет, просто неудачная копипаста. Мне изначально показалось, что list можно будет переиспользовать, но при дальнейшей разработке оказалось, что нет, а я этого не заметила
Исправила

2023-01-18 18:07 UTC, Frilock approved these changes
Принято

2023-01-21 22:27 UTC, merged