Add bookings
Anastassvirs/java-shareit pull request #2
Opened 2023-01-28 05:40 UTC by Anastassvirs

2023-02-01 17:07 UTC, Frilock requested changes
Добрый день, довольно сложная работа, работа с несколькими базами это важные моменты и тут иногда бывает сложно разобраться. Не переживайте.
Смотрите, оставил Вам довольно много комментариев, но в целом они не такие критичные и не такие большие, но повозиться придется.

2023-02-01 17:07 UTC, Frilock commented on pom.xml
> +        <dependency>
Нужно разобраться с gitignore файлом, часть каких то jar файлов из папки lib попадает на ревью. Такого быть не должно

2023-02-01 17:07 UTC, Frilock commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
Не проходят тесты при сборке, нужно разобраться и поправить код. Если не получится обратитесь к наставнику с вопросом

2023-02-01 17:07 UTC, Frilock commented on pom.xml
> +            <version>3.0</version>
Давайте версию вынесем в properties

2023-02-01 17:07 UTC, Frilock commented on pom.xml
> +                            <version>5.4.17.Final</version>
Аналогично и с другими версиями библиотек

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        userService.findById(ownerId);
Зачем происходит вызов метода findById? Если он реализован для проверки наличия записи в БД, то тут 2 тонких момента:
1. Предложил бы эту логику перенести в сервисы, чтобы в контролере оставался только вызов самого метода сервиса, то есть в данном случае метода create, внутри которого была бы проверка
2. Не правильно для проверки наличия записи в БД просто вызывать метод findById, сделайте над ним обертку, назовите ее, например, checkBookingExist, чтобы данный метод возвращал false или true.

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private State validateState(String state) {
Данный метод лучше перенести прям в сам enum, чтобы он по строке отдавал значение енама

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    private UserRepository userRepository;
Если у Вас поля инициализируются 1 раз, например, только в конструкторе то их можно сделать final

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public Booking toBooking(BookingDto bookingCreationDto) {
Предлагаю в методах маперов проверять входное значение что оно не равно null (иначе будет NPE). Если же вы уверены что оно всегда не null, то поставьте аннотацию для параметра NonNull (от jetbrains вроде пакет) - это нужно для того, чтобы Вам каждый раз не перемещаться по коду в сомнениях, " а может ли этот параметр быть нул или нет"

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public BookingDto(Long id, LocalDateTime start, LocalDateTime end, Long bookerId, Long itemId) {
Можно заменить на аннотацию от lombok - AllArgsConstructor

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
public является значением по умолчанию, его можно не указывать

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
Вообще, не знаю, писал или нет, но можете в IDEA установить плагин sonarlint - статический анализатор кода, подскажет ряд хороших практик и места возможных ошибок

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking() {
Можно заменить на NoArgsConstructor от lombok

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking(LocalDateTime start, LocalDateTime end, Item item) {
А Вам точно нужны все три конструктора?

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Component
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select b from Booking b where b.item.id = ?1 and b.item.owner.id = ?2 and b.start > current_timestamp order by b.start desc")
Вы используете spring-data-jpa, в данной библиотеке Вам сам запрос можно укладывать в названии метода (IDEA подсказывает), а сам Query запрос нужно писать только в тех случаях когда не получается написать запрос в названии метода. Например, в методе search. Так делают для того, что если вы вдруг захотите сменить БД (драйвер БД), вам не пришлось бы переписывать все запросы (синтаксис может отличаться).

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public BookingServiceImpl(BookingRepository repository, ItemServiceImpl itemService, UserServiceImpl userService, BookingMapper bookingMapper) {
Чтобы не писать такие большие конструкторы, можно ставить над классом аннотацию RequiredArgsContructor или AllArgs...

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private final UserServiceImpl userService;
В сигнатуре метода должен быть указан интерфейс, а не его реализация, а спринг сам найдет реализацию и подставит ее сюда

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getItem().getOwner().getId().equals(userId)) {
Следите за лишней вложенностью в ваших методах. В данном случае вы можете инвертировать условие, внутри if бросить исключение, что позволит Вам отказаться от блока else (кусок кода который сейчас в if, можно будет писать без else)

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    public Comment(String text) {
А для чего такой конструктор?

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.equals("")) {
Лучше использовать StringUtils.isBlank(text), чтобы избегать NPE

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(unique = true) // У меня почему-то не работает ограничение, которое я написала при создании таблицы,
Использование данной аннотации это нормально, вы hibernate учите что вот данное поле должно быть уникальным.

2023-02-01 17:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/model/UserDto.java
> -    private Long id;
А почему идентификатор удалили?

2023-02-01 17:07 UTC, Frilock commented on src/main/resources/data.sql
> +DELETE
Давайте в одно строчку будет 1 выражение писать (если оно не длинное) - DELETE from users;

2023-02-01 17:07 UTC, Frilock commented on src/main/resources/shema.sql
> +    name  VARCHAR(255)                            NOT NULL,
Если вы тут указываете размер поля (что правильно), то его так же лучше указывать в аннотации column класса модели, как и другие флаги, например, not null = nullable = false в аннотации

2023-02-01 17:07 UTC, Frilock commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +//Я уже который день бьюсь над тем, что у меня перестала работать h2 и я не могу понять, что случилось.
Напишите мне в пачку вашего наставника, попробую протолкнуть Ваш вопрос

2023-02-01 17:07 UTC, Frilock commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +//Я уже который день бьюсь над тем, что у меня перестала работать h2 и я не могу понять, что случилось.
Разобрался в вашей проблеме. В вашем случае у Вас выполняется скрипт data.sql, где идет обращение к таблицам, которых еще/уже нет. Если уберете скрипт то контекст создается. Так что перед обращением к таблицам проверяйте их наличие

2023-02-02 10:30 UTC, Anastassvirs commented on src/main/resources/data.sql
> +DELETE
Я изначально и писала в одну строчку, но Idea самостоятельно исправляет на такое написание

2023-02-02 11:01 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/user/model/UserDto.java
> -    private Long id;
Чтобы не давать пользователю лишнюю информацию. У меня, в целом, Dto от Entity отличается только наличием id в данном случае

2023-02-02 11:10 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    public Comment(String text) {
Использовался для создания комментария, тк передается только текст. Я задавала остальные поля в методе сервиса. Исправила на новый вариант

2023-02-02 12:24 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
Да, у меня он установлен, просто я иногда забываю обращать внимание на него. Поправила все, что нашла

2023-02-02 13:04 UTC, Anastassvirs commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select b from Booking b where b.item.id = ?1 and b.item.owner.id = ?2 and b.start > current_timestamp order by b.start desc")
Если я правильно понимаю, методы, которые у меня есть, нельзя описать в названии метода? Не очень поняла, нужно ли что-то поменять

2023-02-02 16:56 UTC, Anastassvirs commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
Я пыталась просить помощи у наставника и ребят, но ни один из видов application.properties, которые у них работают, почему-то не работают для меня. Не представляю, почему они могут не работать. Локально все тесты постман с h2 запускаются.

2023-02-02 20:30 UTC, Frilock requested changes
Добрый вечер! Уже гораздо лучше. Смотрите, когда вы размер полей и разлиные флаги указываете на модели, то используйте аннотацию Column и в ней указываете, например, nullable = false, или lenght...
Кроме того, по поводу запросов. Да Ваши запросы (почти все) должны работать без аннотации Query.

2023-02-02 20:30 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Length(max = 512)
Лучше указывать то все в аннотации Column

2023-02-04 08:56 UTC, Frilock requested changes
Добрый день, мои комментарии Вы в целом поправили, у меня вопросов особо больше нет. Я работу готов принять, но для этого нужна сборка с зелеными тестами. Попробуйте обратиться к коллегам или наставнику если совсем не разобраться с тестами. С моей стороны я работу принять готов

2023-02-09 05:53 UTC, Frilock approved these changes
Принято

2023-02-09 14:22 UTC, merged