Add item requests
Anastassvirs/java-shareit pull request #3
Opened 2023-02-21 10:53 UTC by Anastassvirs

2023-02-21 11:13 UTC, Anastassvirs commented
Правильно ли я понимаю, что у меня не проходит проверка из-за недостаточного покрытия? И что я тогда делаю не так, что покрытие такое маленькое?

2023-02-26 19:44 UTC, Frilock requested changes
Добрый вечер, по работе:
1. Мелкие комментарии по коду
2. По тестам - отсутствуют модификаторы у полей, повозитесь с методами с аннотациями beeforeEach, AfterEach.

2023-02-26 19:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +        return Objects.equals(getId(), that.getId()) && Objects.equals(getStart(), that.getStart()) && Objects.equals(getEnd(), that.getEnd()) && Objects.equals(getBookerId(), that.getBookerId()) &&
В 1 строчку нельзя так писать, слишком длинная строка, будет варнинг. Кроме того, Для такой простой дтошки можете воспользоваться аннотацией equalsAndHashCode от ломбока

2023-02-26 19:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking(Long id, LocalDateTime start, LocalDateTime end, Item item) {
Вам нужны все эти конструкторы?

2023-02-26 19:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                                       @RequestHeader(value = "X-Sharer-User-Id") Long userId) {
Литерал X-Sharer-User-Id повторяется более 3х раз, вынесите его в константу

2023-02-26 19:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public ItemDto(String name, String description, Boolean available) {
Мне кажется или вы создаете специально конструкторы под тесты? Это не очень хорошая практика, пользуйтесь существующими.

2023-02-26 19:44 UTC, Frilock commented on src/test/java/ru/practicum/shareit/DtoTests.java
> +    UserMapper userMapper;
Отсутствуют модификаторы в тестах, необходимо их добавить

2023-02-26 19:44 UTC, Frilock commented on src/test/java/ru/practicum/shareit/DtoTests.java
> +        String description = "description", nameItem = "Name", descriptionItem = "description of item";
в Java в 1 строчку переменные не пишут. Разделите их

2023-02-26 19:44 UTC, Frilock commented on src/test/java/ru/practicum/shareit/DtoTests.java
> +        User user = new User(requestorId, userName, "anastasia.svir@mail.com");
Чтобы в каждом тесте не создавать тот или иной объект, вы можете сделать 2 метода, например, init и destroy, и пометить их аннотация BeforeEach и AfterEach соответственно и логику перенести туда. Например, в первом методе создавать обьекты для тестов, а в другом очищать данные

2023-02-26 19:44 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTests.java
> +        System.out.println(items);
Это для чего? Уберите это, лишнее

2023-02-26 19:44 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/ItemServiceTests.java
> +        thrown = catchThrowable(() -> {
Можно воспользоваться assertThrown, а для того чтобы проверить что исключений не было - assertDoesNotThrow

2023-03-07 11:10 UTC, Anastassvirs commented on src/test/java/ru/practicum/shareit/item/ItemServiceTests.java
> +        thrown = catchThrowable(() -> {
Не очень поняла, зачем здесь заменять на assertThrown. Кажется, что получится то же самое. Предполагается представить это в таком виде: 
@Test
void testExpectedException() {
  ApplicationException thrown = Assertions.assertThrows(ApplicationException.class, () -> {
           //Code under test
  });
  Assertions.assertEquals("some message", exception.getMessage());
}
?

2023-03-08 08:59 UTC, Frilock approved these changes
Принято

2023-03-08 08:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode
Забыл написать, что по моему данная аннотация входит в Data и ее явно проставлять не нужно

2023-03-08 08:59 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/ItemServiceTests.java
> +        thrown = catchThrowable(() -> {
Да в целом можно и так, не заметил, что вы внизу сообщение проверяете

2023-03-09 09:07 UTC, merged