add docker
Anastassvirs/java-shareit pull request #4
Opened 2023-03-17 13:03 UTC by Anastassvirs

2023-03-19 20:16 UTC, Frilock requested changes
Добрый вечер, посмотрел, в целом хорошо. Есть ряд нюансов:
1. Вижу валидацию вы удалили из подмодуля server, однако зависимость осталась - нужно убрать
2. Комментарий по пом файлу, правильно зависимости добавлять в 1й точке - корневом пом файле.
3. Тесты по валидации по хорошему бы перенести в gateway (но не критично в целом).

2023-03-19 20:16 UTC, Frilock commented on docker-compose.yml
> +version: '3.8'
Не проходят проверки от практикума. Нужно разобраться и поправить

2023-03-19 20:16 UTC, Frilock commented on server/pom.xml
> +        <dependency>
Данной зависимости не должно быть в подмодуле сервера, логика в том, чтобы перенести валидацию входных данных в gateway

2023-03-19 20:16 UTC, Frilock commented on server/pom.xml
> +    <properties>
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х подмодулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

То есть задача в корневом пом файле создать блок dependencyManager и перенести добавление зависимостей с версиями туда. А в других подмодулях уже подключать без указания конкретной версии (подтянется из корневого пом файла)

2023-03-19 20:16 UTC, Frilock commented on server/src/test/java/ru/practicum/shareit/request/ServerRequestControllerTests.java
> -    void createRequestFutureCreated() throws Exception {
По хорошему тесты на валидацию надо бы перенести в gateway

2023-03-20 11:57 UTC, Anastassvirs commented on server/src/test/java/ru/practicum/shareit/request/ServerRequestControllerTests.java
> -    void createRequestFutureCreated() throws Exception {
так у меня же все удаленные тесты и лежат в gateway.. или нужно их не просто перенести в другую папку, а еще что-то сделать?

2023-03-24 18:03 UTC, Anastassvirs commented on server/src/test/java/ru/practicum/shareit/request/ServerRequestControllerTests.java
> -    void createRequestFutureCreated() throws Exception {
Они же уже перенесены туда. Или это нужно сделать как-то иначе?

2023-03-25 22:29 UTC, Anastassvirs commented on server/pom.xml
> +        <dependency>
Но у нас же остаются тесты для сервисов в shareit-server.. Почему этой зависимости не должно быть?

2023-03-25 23:17 UTC, Anastassvirs commented on server/pom.xml
> +    <properties>
локально такое решение у меня работает, а тесты github падают с сообщением о том, что пропущена версия для dependencies. Пример: "'build.plugins.plugin[org.apache.maven.plugins:maven-checkstyle-plugin].dependencies.dependency.version' for org.postgresql:postgresql:jar is missing. @ line 143, column 37"

Я что-то делаю не так?

2023-03-26 09:42 UTC, Frilock approved these changes
Добрый день, принимаю. По поводу комментария с pom файлом, мне так просто по вашему сообщению не разобраться. Но вообще у Вас сделано все практически верно. В кореновом pom файле располагаете блок с dependencyManager и добавляете там зависимости, а затем в других пом файлах их подключаете, но уже без указания версии, указывая только groupId и artifactId. У Вас там с версией посгреса некоторая путаница, а так нормально.

2023-03-26 09:42 UTC, Frilock commented on server/pom.xml
> +            <version>${postgres.version}</version>
Версию postres Вы указали в корневом пом, тут можно просто писать без тега версии

2023-03-26 22:25 UTC, merged